/**
 * Conversation Engine — Task 05 / Phase 7
 *
 * Core dialogue loop: user message → AI reply → summary confirmation → Wiki generation.
 * No dependency on WeeklyReviewRun, WeeklyOrchestrator, or topic cursors.
 *
 * Key safety rules enforced here:
 *  1. AI can only produce `ai_inferred` or `to_verify` — never `user_confirmed`.
 *  2. `user_confirmed` only generated by the engine when user explicitly confirms.
 *  3. AI asks exactly one question per turn.
 *  4. Confirmation produces a wiki conclusion (persistence handled by composition layer).
 *  5. `endWithoutConclusion` produces no Wiki.
 */

import { z } from "zod";
import type { AiProvider, AiCompletionRequest, AiMessage } from "../ai/provider";
import { AiProviderError } from "../ai/provider";
import type { CognitiveContext } from "../context/cognitive-context";
import type {
  Conversation,
  ConversationSeed,
  ConversationTurn,
} from "./model";
import {
  appendTurn,
  requestSummaryConfirmation,
  resumeConversation,
  completeConversation,
} from "./model";
import type { Clock } from "./model";
import { classifyConversationError } from "./error-classifier";

// ═══════════════════════════════════════════════════════════════
// AI Output Schema (Zod)
// ═══════════════════════════════════════════════════════════════

/**
 * The AI output schema for conversation turns.
 *
 * CRITICAL: `epistemic_status` enum is intentionally restricted to
 * `ai_inferred` and `to_verify`. `user_confirmed` CANNOT appear here —
 * it is exclusively produced by the engine after user confirmation.
 */
export const conversationAiOutputSchema = z.object({
  /** Natural-language reply shown to the user. */
  response_text: z.string().min(1),

  /** Structured candidates proposed by AI. */
  candidates: z.array(
    z.object({
      /** MUST be ai_inferred or to_verify — NEVER user_confirmed. */
      epistemic_status: z.enum(["ai_inferred", "to_verify"]),
      canonical_text: z.string().min(1),
      evidence_refs: z.array(z.string()),
      confidence: z.number().min(0).max(1).optional(),
    }),
  ),

  /** Whether AI believes the discussion is mature enough for a summary. */
  should_summarize: z.boolean().default(false),

  /** Summary text — required when should_summarize is true. Accepts null as absent. */
  summary: z.string().nullable().optional(),

  /** Whether AI thinks the conclusion deserves a persistent Wiki page. */
  should_generate_wiki: z.boolean().default(false),

  /** Wiki-ready conclusion text — required when should_generate_wiki is true. */
  wiki_conclusion: z.string().nullable().optional(),

  /** The single most important next question. Exactly one. */
  question: z.string().min(1),
}).superRefine((data, ctx) => {
  // Enforce: summary is required when should_summarize is true
  if (data.should_summarize && (!data.summary || data.summary.trim().length === 0)) {
    ctx.addIssue({
      code: z.ZodIssueCode.custom,
      path: ["summary"],
      message: "Summary is required when should_summarize is true",
    });
  }
  // Enforce: wiki_conclusion is required when should_generate_wiki is true
  if (data.should_generate_wiki && (!data.wiki_conclusion || data.wiki_conclusion.trim().length === 0)) {
    ctx.addIssue({
      code: z.ZodIssueCode.custom,
      path: ["wiki_conclusion"],
      message: "wiki_conclusion is required when should_generate_wiki is true",
    });
  }
});

export type ConversationAiOutput = z.infer<typeof conversationAiOutputSchema>;

// ═══════════════════════════════════════════════════════════════
// Public Types
// ═══════════════════════════════════════════════════════════════

export interface AiCandidate {
  readonly epistemic_status: "ai_inferred" | "to_verify";
  readonly canonical_text: string;
  readonly evidence_refs: readonly string[];
  readonly confidence?: number | undefined;
}

export interface AiResponse {
  readonly text: string;
  readonly internal: {
    readonly candidates: readonly AiCandidate[];
    readonly should_summarize: boolean;
    readonly summary?: string | undefined;
    readonly question: string;
    readonly should_generate_wiki: boolean;
    readonly wiki_conclusion?: string | undefined;
  };
}

export interface ConversationTurnResult {
  readonly conversation: Conversation;
  readonly aiResponse: AiResponse;
  readonly newCandidates: readonly AiCandidate[];
  readonly awaitingConfirmation: boolean;
  readonly summaryText?: string | undefined;
}

export interface ConfirmationResult {
  readonly conversation: Conversation;
  readonly action: "confirmed" | "modified" | "rejected" | "continued";
  /** The confirmed conclusion text — may be used for Wiki generation. */
  readonly wikiConclution: string | null;
}

// ═══════════════════════════════════════════════════════════════
// Prompt Builder
// ═══════════════════════════════════════════════════════════════

const DEFAULT_SYSTEM_INSTRUCTIONS = `你是一个认知助手，帮助用户梳理和深化他们的想法。

核心规则：
1. 一次只问一个最重要的问题。每轮对话只追问一个关键点。
2. 你只能提出 "ai_inferred"（AI推断）或 "to_verify"（待验证）的观点。永远不能声称用户已确认某个观点。
3. 当你认为讨论已经充分，主动提出一段简短总结（2-3句话），并附带一个确认问题。
4. 如果讨论得出了有价值的结论——可复用的原则、方法、规律、洞察——将 should_generate_wiki 设为 true，并在 wiki_conclusion 中写出适合沉淀为 Wiki 页面的完整结论。如果只是定义查询或简单事实，should_generate_wiki 为 false。
5. 用中文回复。

尽量以下面的 JSON 格式回复（如果无法生成 JSON，纯文本回复也可以接受）：
{
  "response_text": "你的自然语言回复",
  "candidates": [{ "epistemic_status": "ai_inferred 或 to_verify", "canonical_text": "简洁的候选观点", "evidence_refs": ["引用来源"], "confidence": 0.0-1.0 }],
  "should_summarize": true或false,
  "summary": "简短总结（should_summarize为true时必填）",
  "should_generate_wiki": true或false,
  "wiki_conclusion": "完整结论正文（should_generate_wiki为true时必填）",
  "question": "下一个要问的问题"
}`;

/**
 * Build a structured prompt for the AI from conversation history + cognitive context.
 */
export function buildConversationPrompt(
  conversation: Conversation,
  userText: string,
  context: CognitiveContext,
  systemInstructions: string = DEFAULT_SYSTEM_INSTRUCTIONS,
): AiCompletionRequest<ConversationAiOutput> {
  const messages: AiMessage[] = [];

  // ── System message ──────────────────────────────────────
  let systemContent = systemInstructions;

  // Append cognitive context if available
  if (context.vaultSnippets.length > 0) {
    systemContent += "\n\n## 相关笔记片段\n\n";
    for (const snippet of context.vaultSnippets) {
      // Format note title: truncate long titles with ellipsis
      const title = snippet.note_title.length > 40
        ? snippet.note_title.slice(0, 37) + "..."
        : snippet.note_title;
      systemContent += `【${title}】\n${snippet.snippet}\n\n`;
    }
  }

  if (context.wikiSnippets && context.wikiSnippets.length > 0) {
    systemContent += "\n## 相关 Wiki 结论\n\n";
    for (const ws of context.wikiSnippets) {
      systemContent += `- [Wiki: ${ws.title}] ${ws.snippet}\n`;
    }
  }

  messages.push({ role: "system", content: systemContent });

  // ── Conversation history (truncated to prevent context overflow) ──
  // Keep only the most recent turns to stay within model context window.
  // Each turn is ~200-500 tokens; 12 turns ≈ 6K tokens, leaving room for
  // system prompt, cognitive context, and AI response.
  const MAX_TURNS = 12;
  const recentTurns = conversation.turns.length > MAX_TURNS
    ? conversation.turns.slice(-MAX_TURNS)
    : conversation.turns;

  if (conversation.turns.length > MAX_TURNS) {
    messages.push({
      role: "system",
      content: `[对话摘要：前 ${conversation.turns.length - MAX_TURNS} 轮已省略，以下是最近的对话]`,
    });
  }

  for (const turn of recentTurns) {
    messages.push({ role: turn.role, content: turn.text });
  }

  // ── Current user input ──────────────────────────────────
  // KI-T11-01 fix: Avoid double-appending the user message.
  // When the composition layer has already appended the user turn to
  // conversation.turns before calling the engine, we must not add it again.
  // Check if the last turn is already this exact user message.
  const lastTurn = conversation.turns[conversation.turns.length - 1];
  if (!lastTurn || lastTurn.role !== 'user' || lastTurn.text !== userText) {
    messages.push({ role: "user", content: userText });
  }

  return {
    messages,
    outputSchema: conversationAiOutputSchema,
    outputName: "conversation_ai_output",
    temperature: 0.7,
  };
}

// ═══════════════════════════════════════════════════════════════
// Confirmation Intent Classifier
// ═══════════════════════════════════════════════════════════════

/**
 * Classify user intent when they respond to a summary confirmation.
 *
 * Simple deterministic keyword matching — no AI call needed for this.
 * Returns the classified action.
 */
export function classifyConfirmationIntent(
  userText: string,
): "confirmed" | "modified" | "rejected" | "continued" {
  const text = userText.trim().toLowerCase();

  // ── Modification signals (check first — modification overrides confirmation) ─
  const modifyKeywords = ["改成", "修改", "应该是", "更准确地说", "更正", "change", "modify", "correct"];
  for (const kw of modifyKeywords) {
    if (text.includes(kw)) return "modified";
  }

  // ── Rejection signals ───────────────────────────────────
  const rejectKeywords = ["不对", "不是", "错了", "不正确", "不同意", "错误", "no", "wrong", "disagree", "incorrect"];
  for (const kw of rejectKeywords) {
    if (text.includes(kw)) return "rejected";
  }

  // ── Continuation signals ────────────────────────────────
  const continueKeywords = ["继续", "再聊", "再谈谈", "等等", "还有", "其他", "more", "continue", "discuss", "further"];
  for (const kw of continueKeywords) {
    if (text.includes(kw)) return "continued";
  }

  // ── Confirmation signals ────────────────────────────────
  const confirmKeywords = [
    "好的", "同意", "确认", "对", "是的", "没错", "可以", "没问题",
    "yes", "ok", "agree", "confirm", "correct", "right", "sure",
    "行", "赞成", "没问题",
  ];
  for (const kw of confirmKeywords) {
    if (text.includes(kw)) return "confirmed";
  }

  // ── Default: ambiguous → continue discussion ────────────
  return "continued";
}

// ═══════════════════════════════════════════════════════════════
// Conversation Engine
// ═══════════════════════════════════════════════════════════════

export class ConversationEngine {
  constructor(
    private readonly aiProvider: AiProvider,
    private readonly clock: Clock = { now: () => new Date() },
  ) {}

  // ── sendMessage ──────────────────────────────────────────

  /**
   * Send a user message and get an AI reply.
   *
   * Validates conversation is active, builds prompt, calls AI,
   * validates the response (no user_confirmed), and updates the conversation.
   *
   * When the AI proposes a summary (should_summarize=true), the conversation
   * transitions to `awaiting_summary_confirmation`.
   *
   * @throws {AiProviderError} if AI returns `user_confirmed` in candidates
   * @throws {Error} if conversation is not active
   */
  async sendMessage(
    conversation: Conversation,
    userText: string,
    context: CognitiveContext,
  ): Promise<ConversationTurnResult> {
    // 1. Validate state
    if (conversation.status !== "active") {
      throw new Error(
        `Cannot send message: conversation is ${conversation.status}, expected active`,
      );
    }

    // 2. Use conversation as-is (caller is responsible for persisting user turn)
    //    The user turn may already be in conversation.turns if appended by the
    //    composition layer. The prompt builder handles deduplication of userText.
    let conv = conversation;

    // 3. Build prompt
    const request = buildConversationPrompt(conv, userText, context);

    // 4. Call AI
    let rawOutput: ConversationAiOutput;
    try {
      rawOutput = await this.aiProvider.complete(request);
    } catch (error) {
      if (error instanceof AiProviderError) throw error;
      // Sanitize: strip API keys, tokens, paths from error messages
      const classified = classifyConversationError(error);
      throw new AiProviderError("transport", classified.message);
    }

    // 5. Validate AI output defensively
    //    First, validate against the schema (defense in depth — the real
    //    AiProvider also validates, but the engine must not trust it).
    const parseResult = conversationAiOutputSchema.safeParse(rawOutput);
    if (!parseResult.success) {
      throw new AiProviderError(
        "invalid_output",
        `AI output failed schema validation: ${parseResult.error.issues.map((i) => i.message).join("; ")}`,
      );
    }
    // Second, check the critical security constraint
    this.validateAiOutput(parseResult.data);

    const validated = parseResult.data;

    // 6. Build AI response
    const aiResponse: AiResponse = {
      text: validated.response_text,
      internal: {
        candidates: validated.candidates.map((c) => ({
          epistemic_status: c.epistemic_status,
          canonical_text: c.canonical_text,
          evidence_refs: c.evidence_refs,
          confidence: c.confidence,
        })),
        should_summarize: validated.should_summarize,
        summary: validated.summary ?? undefined,
        question: validated.question,
        should_generate_wiki: validated.should_generate_wiki,
        wiki_conclusion: validated.wiki_conclusion ?? undefined,
      },
    };

    const newCandidates: AiCandidate[] = validated.candidates.map((c) => ({
      epistemic_status: c.epistemic_status,
      canonical_text: c.canonical_text,
      evidence_refs: c.evidence_refs,
      confidence: c.confidence,
    }));

    // 7. Append AI turn
    conv = appendTurn(conv, "assistant", validated.response_text, this.clock);

    // 8. Handle summary confirmation request
    let awaitingConfirmation = false;
    let summaryText: string | undefined;

    if (validated.should_summarize && validated.summary) {
      // KI-T11-01 fix: requestSummaryConfirmation already appends the candidate
      // as an assistant turn internally. Removed redundant appendTurn to prevent
      // double revision increment in the summary confirmation flow.
      conv = requestSummaryConfirmation(conv, validated.summary, this.clock);
      awaitingConfirmation = true;
      summaryText = validated.summary;
    }

    return {
      conversation: conv,
      aiResponse,
      newCandidates,
      awaitingConfirmation,
      summaryText,
    };
  }

  async concludeConversation(
    conversation: Conversation,
    context: CognitiveContext,
  ): Promise<ConversationTurnResult> {
    const instruction = [
      "请基于以上全部对话生成最终结论。",
      "覆盖用户表达的主要细节，不要只给笼统概括。",
      "每条结论使用数字编号并独立成段，条目之间空一行。",
      "每条注明认识状态：AI推断或待验证。",
      "不要继续追问。",
    ].join("\n");

    const result = await this.sendMessage(conversation, instruction, context);
    const summaryText = result.summaryText ?? result.aiResponse.text;
    const awaiting = requestSummaryConfirmation(
      conversation,
      summaryText,
      this.clock,
    );

    return {
      conversation: awaiting,
      aiResponse: {
        ...result.aiResponse,
        internal: {
          ...result.aiResponse.internal,
          should_summarize: true,
          summary: summaryText,
        },
      },
      newCandidates: result.newCandidates,
      awaitingConfirmation: true,
      summaryText,
    };
  }

  // ── handleConfirmationResponse ───────────────────────────

  /**
   * Handle the user's response to a summary confirmation.
   *
   * Classifies intent and acts accordingly:
   *  - confirmed → generate user_confirmed claims, commit writeback, complete
   *  - modified → generate user_confirmed claims with user's text, commit, complete
   *  - rejected → return to active
   *  - continued → return to active
   *
   * Writeback failure DOES NOT complete the conversation.
   *
   * @throws {Error} if conversation is not `awaiting_summary_confirmation`
   */
  async handleConfirmationResponse(
    conversation: Conversation,
    userText: string,
    context: CognitiveContext,
  ): Promise<ConfirmationResult> {
    // 1. Validate state
    if (conversation.status !== "awaiting_summary_confirmation") {
      throw new Error(
        `Cannot handle confirmation: conversation is ${conversation.status}, expected awaiting_summary_confirmation`,
      );
    }

    // 2. Classify intent
    const intent = classifyConfirmationIntent(userText);

    // 3. Handle each intent
    switch (intent) {
      case "confirmed":
        return this.handleConfirmed(conversation, userText, false);

      case "modified":
        return this.handleConfirmed(conversation, userText, true);

      case "rejected": {
        // Return to active — user disagrees with summary
        const resumed = resumeConversation(conversation, this.clock);
        const withTurn = appendTurn(resumed, "user", userText, this.clock);
        return {
          conversation: withTurn,
          action: "rejected",
          wikiConclution: null,
        };
      }

      case "continued": {
        // Return to active — user wants more discussion
        const resumed = resumeConversation(conversation, this.clock);
        const withTurn = appendTurn(resumed, "user", userText, this.clock);
        return {
          conversation: withTurn,
          action: "continued",
          wikiConclution: null,
        };
      }

      default:
        // Should never reach here
        throw new Error(`Unknown confirmation intent: ${intent}`);
    }
  }

  // ── endWithoutConclusion ─────────────────────────────────

  /**
   * End an active conversation without saving any formal claims.
   * The conversation is archived but no claims are written to the model.
   *
   * @throws {Error} if conversation is not active
   */
  async endWithoutConclusion(conversation: Conversation): Promise<Conversation> {
    if (conversation.status !== "active") {
      throw new Error(
        `Cannot end: conversation is ${conversation.status}, expected active`,
      );
    }
    return completeConversation(conversation, "no_formal_result", this.clock);
  }

  // ═══════════════════════════════════════════════════════════
  // Internal Helpers
  // ═══════════════════════════════════════════════════════════

  /**
   * Validate that the AI output does not contain `user_confirmed`.
   * This is a critical security boundary — AI must never claim user confirmation.
   */
  private validateAiOutput(output: ConversationAiOutput): void {
    for (const candidate of output.candidates) {
      if ((candidate.epistemic_status as string) === "user_confirmed") {
        throw new AiProviderError(
          "invalid_output",
          "AI returned 'user_confirmed' in candidates. "
          + "Only the engine can produce user_confirmed status. "
          + "This is a security boundary violation — the response has been rejected.",
        );
      }
    }
  }

  /**
   * Handle a user's confirmation (direct or modified).
   *
   * Extracts the confirmed conclusion text for potential Wiki generation.
   * The actual Wiki file writing is handled by the composition layer
   * (composition-conversation.ts) — the engine only produces the text.
   */
  private async handleConfirmed(
    conversation: Conversation,
    userText: string,
    isModified: boolean,
  ): Promise<ConfirmationResult> {
    // Extract the conclusion text from the conversation
    let wikiConclution: string | null = null;

    if (isModified) {
      // User modified the summary — their text IS the conclusion
      wikiConclution = userText.trim();
    } else {
      // Use the last assistant turn as the conclusion
      // (requestSummaryConfirmation stores the proposed summary there)
      const aiTurns = conversation.turns.filter((t) => t.role === "assistant");
      const lastAiTurn = aiTurns[aiTurns.length - 1];
      if (lastAiTurn && lastAiTurn.text.trim().length > 0) {
        wikiConclution = lastAiTurn.text.trim();
      }
    }

    // Append user confirmation turn and complete the conversation
    let conv = appendTurn(conversation, "user", userText, this.clock);
    conv = completeConversation(conv, "confirmed_results", this.clock);

    return {
      conversation: conv,
      action: isModified ? "modified" : "confirmed",
      wikiConclution,
    };
  }
}
